//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionarios.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Concesionarios.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los apellidos no pueden ser vacíos o nulos.
        /// </summary>
        internal static string ClienteApellidosNotNullOrEmpty {
            get {
                return ResourceManager.GetString("ClienteApellidosNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no puede ser vacío o nulo.
        /// </summary>
        internal static string ClienteNombreNotNullOrEmpty {
            get {
                return ResourceManager.GetString("ClienteNombreNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El telefono no debe ser nulo.
        /// </summary>
        internal static string ClienteTelefonoNotNull {
            get {
                return ResourceManager.GetString("ClienteTelefonoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente debe tener un identificador valido.
        /// </summary>
        internal static string PrespuestoClienteMustHaveValidId {
            get {
                return ResourceManager.GetString("PrespuestoClienteMustHaveValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente no puede ser nulo.
        /// </summary>
        internal static string PrespuestoClienteNotNull {
            get {
                return ResourceManager.GetString("PrespuestoClienteNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehiculo debe tener un identificador valido.
        /// </summary>
        internal static string PrespuestoVehiculoMustHaveValidId {
            get {
                return ResourceManager.GetString("PrespuestoVehiculoMustHaveValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prespuesto cerrado, debes reabrirlo para poder aceptarlo.
        /// </summary>
        internal static string PresupuestoAceptarNotCerrado {
            get {
                return ResourceManager.GetString("PresupuestoAceptarNotCerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto ya cerrado.
        /// </summary>
        internal static string PresupuestoCerrarNotCerrado {
            get {
                return ResourceManager.GetString("PresupuestoCerrarNotCerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe del presupuesto debe ser mayor que cero.
        /// </summary>
        internal static string PresupuestoImporteGreatherThanZero {
            get {
                return ResourceManager.GetString("PresupuestoImporteGreatherThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto ya abierto.
        /// </summary>
        internal static string PresupuestoReabrirNotAbierto {
            get {
                return ResourceManager.GetString("PresupuestoReabrirNotAbierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El vehiculo no puede ser nulo.
        /// </summary>
        internal static string PreuspuestoVehiculoNotNull {
            get {
                return ResourceManager.GetString("PreuspuestoVehiculoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La marca no puede ser vacia o nula.
        /// </summary>
        internal static string VehiculoMarcaNotNullOrEmpty {
            get {
                return ResourceManager.GetString("VehiculoMarcaNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo no puede ser vacío o nulo.
        /// </summary>
        internal static string VehiculoModeloNotNullOrEmpty {
            get {
                return ResourceManager.GetString("VehiculoModeloNotNullOrEmpty", resourceCulture);
            }
        }
    }
}
